project_id = "qzqlwbzvzjaxzdrhamow"

[functions.auth_start]
verify_jwt = true

[functions.auth_callback]
verify_jwt = false

[functions.generate-content]
verify_jwt = true

[functions.publish-pin]
verify_jwt = true
