project_id = "qzqlwbzvzjaxzdrhamow"

[functions.auth_start]
verify_jwt = true

[functions.auth_callback]
verify_jwt = false

[functions.generate-content]
verify_jwt = true

[functions.publish-pin]
verify_jwt = true

[functions.publish-linkedin]
verify_jwt = true


[storage.buckets.studio-media-public]
public = true
file_size_limit = "10MiB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp"]
