import { useState, useMemo, useEffect } from 'react';
import type { UseWorkflowReturn } from '@/hooks/useWorkflow';
import { useWeeklyBatch } from '@/hooks/useWeeklyBatch';
import { useContentData } from '@/hooks/useContentData';
import type { ContentItem } from '@/types';
import { getPlatform, getFormat } from '@/data/platforms';
import type { ApprovalDecision, PlatformId } from '@/types';
import {
  CheckCircle2,
  XCircle,
  RotateCcw,
  Clock,
  Lock,
  CheckSquare,
  ListChecks,
  FileCheck,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const DECISION_CONFIG: Record<ApprovalDecision, { label: string; icon: LucideIcon; color: string; bg: string }> = {
  pending: { label: 'Pending', icon: Clock, color: '#94A3B8', bg: '#F1F5F9' },
  approved: { label: 'Approved', icon: CheckCircle2, color: '#10B981', bg: '#ECFDF5' },
  rejected: { label: 'Rejected', icon: XCircle, color: '#EF4444', bg: '#FEF2F2' },
  revisions: { label: 'Needs Revision', icon: RotateCcw, color: '#F59E0B', bg: '#FFFBEB' },
};

const REVIEW_CHECKLIST = [
  { id: 'brand', label: 'Content aligns with brand voice and guidelines' },
  { id: 'accuracy', label: 'All claims, data, and references are accurate' },
  { id: 'format', label: 'Format matches platform requirements (dimensions, length)' },
  { id: 'tone', label: 'Tone is appropriate for the target audience' },
  { id: 'cta', label: 'Call to action is clear and actionable' },
  { id: 'assets', label: 'Supporting assets (visuals, thumbnails) are ready' },
];

interface WeeklyApprovalViewProps {
  workflow: UseWorkflowReturn;
}

export function WeeklyApprovalView({ workflow }: WeeklyApprovalViewProps) {
  const { approvalBatches, setApprovalDecision, closeBatch, refreshApprovals } = workflow;
  const { batchId, weekLabel, items: weekItems, addToBatch } = useWeeklyBatch();
  const { content } = useContentData();

  // Content items in ideation/drafting that aren't in any batch yet
  const unbatchedContent = useMemo(() => {
    const batchedIds = new Set(approvalBatches.flatMap((b) => b.items.map((i) => i.contentId)));
    return content.filter(
      (c) => ['ideation', 'drafting'].includes(c.stage) && !batchedIds.has(c.id)
    );
  }, [content, approvalBatches]);
  const [activeBatchId, setActiveBatchId] = useState(
    approvalBatches.find((b) => b.status === 'open')?.id || approvalBatches[0]?.id || ''
  );
  const [reviewerName, setReviewerName] = useState('');
  const [checklistState, setChecklistState] = useState<Record<string, boolean>>({});
  const [approvalError, setApprovalError] = useState<string | null>(null);

  useEffect(() => {
    void refreshApprovals().catch((error) => {
      setApprovalError(error instanceof Error ? error.message : 'Could not refresh approvals.');
    });
  }, [refreshApprovals]);

  useEffect(() => {
    if (!activeBatchId || !approvalBatches.some((batch) => batch.id === activeBatchId)) {
      setActiveBatchId(
        approvalBatches.find((batch) => batch.status === 'open')?.id || approvalBatches[0]?.id || ''
      );
    }
  }, [approvalBatches, activeBatchId]);

  const activeBatch = useMemo(
    () => approvalBatches.find((b) => b.id === activeBatchId) || approvalBatches[0],
    [approvalBatches, activeBatchId]
  );

  if (!activeBatch) return null;

  const decisionCounts = activeBatch.items.reduce(
    (acc, item) => {
      acc[item.decision] = (acc[item.decision] || 0) + 1;
      return acc;
    },
    {} as Record<ApprovalDecision, number>
  );

  const allChecked = REVIEW_CHECKLIST.every((c) => checklistState[c.id]);

  const handleDecision = async (contentId: string, decision: ApprovalDecision) => {
    setApprovalError(null);
    try {
      await setApprovalDecision(activeBatch.id, contentId, decision, reviewerName || 'Reviewer', '');
    } catch (error) {
      setApprovalError(error instanceof Error ? error.message : 'Could not save approval decision.');
    }
  };

  const handleCloseBatch = async () => {
    setApprovalError(null);
    try {
      await closeBatch(activeBatch.id);
    } catch (error) {
      setApprovalError(error instanceof Error ? error.message : 'Could not close approval batch.');
    }
  };

  const activePendingApprovals = activeBatch.items.filter((item) => item.decision === 'pending').length;

  return (
    <div className="p-8 max-w-6xl mx-auto">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-slate-100 mb-1">Weekly Approval</h2>
        <p className="text-sm text-slate-500">
          One weekly pass to review, approve, or reject all content generated by the daily workflow.
          Only approved content moves to scheduling and handoff.
        </p>
      </div>

      {approvalError && (
        <div className="mb-5 rounded-xl border border-rose-400/20 bg-rose-400/[0.05] px-4 py-3 text-sm text-rose-300">
          Approval error: {approvalError}
        </div>
      )}

      {/* Batch Selector */}
      <div className="flex items-center gap-2 mb-6">
        {approvalBatches.map((batch) => {
          const isActive = batch.id === activeBatchId;
          const pending = batch.items.filter((i) => i.decision === 'pending').length;
          return (
            <button
              key={batch.id}
              onClick={() => setActiveBatchId(batch.id)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
                isActive
                  ? 'bg-slate-900 text-white'
                  : 'bg-[#0b1118] border border-[#1b2935] text-slate-400 hover:bg-[#070b10]'
              }`}
            >
              <span>{batch.weekLabel}</span>
              {batch.status === 'open' ? (
                <span className={`text-[10px] px-1.5 py-0.5 rounded-full ${
                  isActive ? 'bg-[#0b1118]/20 text-white' : 'bg-amber-100 text-amber-200/75'
                }`}>
                  {pending} pending
                </span>
              ) : (
                <Lock size={12} className={isActive ? 'text-white/60' : 'text-slate-400'} />
              )}
            </button>
          );
        })}
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-4 gap-3 mb-6">
        {(Object.keys(DECISION_CONFIG) as ApprovalDecision[]).map((decision) => {
          const cfg = DECISION_CONFIG[decision];
          const Icon = cfg.icon;
          const count = decisionCounts[decision] || 0;
          return (
            <div
              key={decision}
              className="bg-[#0b1118] border border-[#1b2935] rounded-xl p-4"
            >
              <div className="flex items-center gap-2 mb-2">
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: cfg.bg }}
                >
                  <Icon size={15} style={{ color: cfg.color }} />
                </div>
              </div>
              <p className="text-xl font-bold text-slate-100">{count}</p>
              <p className="text-xs text-slate-500">{cfg.label}</p>
            </div>
          );
        })}
      </div>

      {/* Review Checklist */}
      {activeBatch.status === 'open' && (
        <div className="bg-[#0b1118] border border-[#1b2935] rounded-xl p-5 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <ListChecks size={16} className="text-sky-500" />
            <h3 className="text-sm font-semibold text-slate-300">Review Checklist</h3>
            <span className="text-xs text-slate-400">
              ({Object.values(checklistState).filter(Boolean).length}/{REVIEW_CHECKLIST.length} checked)
            </span>
          </div>
          <div className="grid grid-cols-2 gap-2 mb-4">
            {REVIEW_CHECKLIST.map((item) => {
              const checked = checklistState[item.id] || false;
              return (
                <button
                  key={item.id}
                  onClick={() =>
                    setChecklistState((prev) => ({ ...prev, [item.id]: !prev[item.id] }))
                  }
                  className={`flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-sm text-left transition-all ${
                    checked
                      ? 'bg-emerald-400/[0.045] text-emerald-700 border border-emerald-400/20'
                      : 'bg-[#070b10] text-slate-400 border border-[#1b2935] hover:bg-[#101820]'
                  }`}
                >
                  <div
                    className={`w-5 h-5 rounded-md flex items-center justify-center shrink-0 transition-all ${
                      checked ? 'bg-emerald-500' : 'bg-[#0b1118] border border-slate-300'
                    }`}
                  >
                    {checked && <CheckSquare size={12} className="text-white" />}
                  </div>
                  <span className="text-xs">{item.label}</span>
                </button>
              );
            })}
          </div>

          <div className="flex items-center gap-3 pt-4 border-t border-[#14202a]">
            <input
              type="text"
              value={reviewerName}
              onChange={(e) => setReviewerName(e.target.value)}
              placeholder="Reviewer name..."
              className="flex-1 px-3 py-2 text-sm bg-[#070b10] border border-[#1b2935] rounded-lg outline-none transition-all focus:bg-[#0b1118] focus:border-sky-300 focus:ring-2 focus:ring-sky-100 placeholder:text-slate-400"
            />
            <button
              onClick={handleCloseBatch}
              disabled={!allChecked || activePendingApprovals > 0}
              className={`flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-lg transition-all ${
                allChecked && activePendingApprovals === 0
                  ? 'bg-emerald-500 text-white hover:bg-emerald-600 shadow-sm'
                  : 'bg-slate-200 text-slate-400 cursor-not-allowed'
              }`}
            >
              <FileCheck size={15} />
              Close Batch
            </button>
          </div>
          {activePendingApprovals > 0 && (
            <p className="mt-2 text-xs text-slate-400">
              {activePendingApprovals} item(s) still need a decision before closing.
            </p>
          )}
        </div>
      )}

      {/* Approval Items */}
      <div>
        <h3 className="text-sm font-semibold text-slate-300 mb-3">
          Content for Review — {activeBatch.weekLabel}
        </h3>
        <div className="space-y-2">
          {activeBatch.items.map((item) => {
            const platform = getPlatform(item.platform);
            const format = getFormat(item.format);
            if (!platform || !format) return null;
            const cfg = DECISION_CONFIG[item.decision];
            const DecisionIcon = cfg.icon;
            const isClosed = activeBatch.status === 'closed';

            return (
              <div
                key={item.contentId}
                className="bg-[#0b1118] border border-[#1b2935] rounded-xl p-4 hover:shadow-sm transition-shadow"
              >
                <div className="flex items-center gap-3">
                  <span
                    className="w-8 h-8 rounded-lg flex items-center justify-center text-[10px] font-bold shrink-0"
                    style={{ backgroundColor: `${platform.color}18`, color: platform.color }}
                  >
                    {platform.label[0]}
                  </span>

                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-slate-200 truncate">{item.title}</p>
                    <p className="text-xs text-slate-400">
                      {platform.label} · {format.label}
                      {item.reviewer && ` · Reviewed by ${item.reviewer}`}
                    </p>
                  </div>

                  <span
                    className="flex items-center gap-1 text-[10px] font-medium px-2 py-1 rounded-full shrink-0"
                    style={{ backgroundColor: cfg.bg, color: cfg.color }}
                  >
                    <DecisionIcon size={11} />
                    {cfg.label}
                  </span>

                  {!isClosed && (
                    <div className="flex items-center gap-1.5 shrink-0">
                      <button
                        onClick={() => handleDecision(item.contentId, 'approved')}
                        className={`flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                          item.decision === 'approved'
                            ? 'bg-emerald-500 text-white'
                            : 'bg-emerald-400/[0.045] text-emerald-400 hover:bg-emerald-100'
                        }`}
                      >
                        <CheckCircle2 size={13} />
                        Approve
                      </button>
                      <button
                        onClick={() => handleDecision(item.contentId, 'revisions')}
                        className={`flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                          item.decision === 'revisions'
                            ? 'bg-amber-500 text-white'
                            : 'bg-amber-400/[0.05] text-amber-600 hover:bg-amber-100'
                        }`}
                      >
                        <RotateCcw size={13} />
                        Revise
                      </button>
                      <button
                        onClick={() => handleDecision(item.contentId, 'rejected')}
                        className={`flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                          item.decision === 'rejected'
                            ? 'bg-rose-500 text-white'
                            : 'bg-rose-50 text-rose-600 hover:bg-rose-100'
                        }`}
                      >
                        <XCircle size={13} />
                        Reject
                      </button>
                    </div>
                  )}
                </div>

                {item.notes && (
                  <div className="mt-2 ml-11 pl-3 border-l-2 border-[#1b2935]">
                    <p className="text-xs text-slate-500 italic">{item.notes}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Unbatched Content — items generated but not yet in any approval batch */}
      {unbatchedContent.length > 0 && (
        <div className="mt-8">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-sm font-semibold text-slate-300">Generated, Not Yet in Batch</h3>
              <p className="text-xs text-slate-400 mt-0.5">
                {unbatchedContent.length} item(s) waiting to join this week's review
              </p>
            </div>
            <button
              onClick={async () => {
                setApprovalError(null);
                try {
                  for (const item of unbatchedContent) {
                    await addToBatch(item);
                  }
                  await refreshApprovals();
                } catch (error) {
                  setApprovalError(error instanceof Error ? error.message : 'Could not add content to approval batch.');
                }
              }}
              className="px-3 py-1.5 text-xs font-medium text-cyan-200/75 bg-cyan-400/[0.04] border border-cyan-400/15 rounded-lg hover:bg-sky-100 transition-all"
            >
              Pull All Into Batch
            </button>
          </div>
          <div className="space-y-2">
            {unbatchedContent.map((item) => {
              const platform = getPlatform(item.platform);
              const format = getFormat(item.format);
              return (
                <div
                  key={item.id}
                  className="bg-[#0b1118] border border-dashed border-slate-300 rounded-xl p-4 flex items-center gap-3"
                >
                  <span
                    className="w-8 h-8 rounded-lg flex items-center justify-center text-[10px] font-bold shrink-0"
                    style={{ backgroundColor: `${platform?.color}18`, color: platform?.color }}
                  >
                    {platform?.label[0]}
                  </span>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-slate-200 truncate">{item.title}</p>
                    <p className="text-xs text-slate-400">
                      {platform?.label} · {format?.label} · {item.stage}
                    </p>
                  </div>
                  <button
                    onClick={async () => {
                      setApprovalError(null);
                      try {
                        await addToBatch(item);
                        await refreshApprovals();
                      } catch (error) {
                        setApprovalError(error instanceof Error ? error.message : 'Could not add content to approval batch.');
                      }
                    }}
                    className="px-3 py-1.5 text-xs font-medium text-cyan-200/75 bg-cyan-400/[0.04] border border-cyan-400/15 rounded-lg hover:bg-sky-100 transition-all shrink-0"
                  >
                    + Add
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}